### PR TITLE
Fix bug in handling postgres `COPY` command and a few others

### LINKED ISSUE #533: Postgres `COPY` causes timeouts and connection getting stuck transferring data
## Expected Behavior

The `COPY` command in PSQL should copy data to the given table seamlessly.

## Current Behavior

While importing a large SQL file using `psql` and it uses the [`COPY`](https://www.postgresql.org/docs/current/sql-copy.html) command like [this one](https://github.com/jOOQ/sakila/blob/main/postgres-sakila-db/postgres-sakila-insert-data-using-copy.sql), this results in timeouts and the connection getting stuck transferring data.

## Steps to Reproduce

1. Run an empty PostgreSQL database (using Docker).
2. Run `gatewayd`.
3. Create database schema using [this file](https://github.com/jOOQ/sakila/blob/main/postgres-sakila-db/postgres-sakila-schema.sql) via `psql` while proxying with GatewayD.
4. Import data into the newly created database using [this file](https://github.com/jOOQ/sakila/blob/main/postgres-sakila-db/postgres-sakila-insert-data-using-copy.sql).
5. Observe the behavior: `psql` gets stuck copying data.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Operating System and architecture: Debian 11 (amd64)
- Go Toolchain version: go1.22
- SDK version: v0.2.13
- GatewayD version: v0.9.5
- Plugins' versions: N/A

FYI @sh-soltanpour

## Resources
- https://blog.benthem.io/2023/08/16/what-actually-happens-when-you-run-copy-in-postgres.html
- https://www.postgresql.org/docs/current/sql-copy.html

### PR DESCRIPTION
**Pull request by mostafa**
# Ticket(s)

Closes #533.

## Description

After hours of debugging, I discovered that the issue stemmed from a few incorrect assumptions. The first was that the chunk size read from the connection should be compared to the `ReceiveChunkSize`, rather than the total amount of data received up to that point. The second assumption was that receiving zero data from the server should automatically close the connection, which has since been resolved.

The third assumption was that every request to PostgreSQL would elicit an immediate response, but the behavior of the [`COPY` command](https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-COPY) proved otherwise. When a client issues a `COPY` command to the server, PostgreSQL replies with a `CopyInResponse`. If no errors occur, the client begins sending `CopyData` messages, which may consist of multiple requests, depending on the chunk size. After each `CopyData` message, however, the server does not send an acknowledgment or response—it simply waits. Only when the client sends a `CopyDone` message at the end of the data transmission does the server reply with `CommandComplete` and `ReadyForQuery` messages. This means the client can send multiple requests without receiving an immediate response for each one. The final `ReadyForQuery` response from the server signals that the client can proceed with the next request.

Ref: https://www.postgresql.org/docs/current/protocol-message-formats.html

In order to make sure that it works as expected, I tested the referenced SQL dump file in the issue and it works like a charm. I tested GatewayD with `pgbench` and found out that concurrent reads and writes to the `Server.connectionToProxyMap` causes fatal errors, hence exiting the process. I changed the type to `sync.Map` to avoid this in the future and make GatewayD more stable. Note that the `tps` before and after the change is decreased and the latency is increased, which is expected:

**Before:**
```bash
PGPASSWORD=postgres pgbench -M extended --transactions 100 --jobs 10 --client 99 -h localhost -p 15432 -U postgres postgres
starting vacuum...end.
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 1
query mode: extended
number of clients: 99
number of threads: 10
number of transactions per client: 100
number of transactions actually processed: 9900/9900
latency average = 188.036 ms
tps = 526.495434 (including connections establishing)
tps = 527.065595 (excluding connections establishing)
```

**After:**
```bash
PGPASSWORD=postgres pgbench -M extended --transactions 100 --jobs 10 --client 99 -h localhost -p 15432 -U postgres postgres
starting vacuum...end.
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 1
query mode: extended
number of clients: 99
number of threads: 10
number of transactions per client: 100
number of transactions actually processed: 9900/9900
latency average = 197.091 ms
tps = 502.307211 (including connections establishing)
tps = 502.959156 (excluding connections establishing)
```

CC @sh-soltanpour

## Related PRs

N/A

## Development Checklist

- [x] I have added a descriptive title to this PR.
- [x] I have squashed related commits together.
- [x] I have rebased my branch on top of the latest main branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added docstring(s) to my code.
- [ ] I have made corresponding changes to the documentation (docs).
- [ ] I have updated docs using `make gen-docs` command.
- [ ] I have added tests for my changes.
- [x] I have signed all the commits.

## Legal Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/gatewayd-io/gatewayd/blob/main/CONTRIBUTING.md) document.
- [x] I have read and understood the [Code of Conduct](https://github.com/gatewayd-io/gatewayd/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and agreed to the [Apache CLA](https://www.apache.org/licenses/contributor-agreements.html) (required).
- [x] I have read and agreed to the [LICENSE](https://github.com/gatewayd-io/gatewayd/blob/main/LICENSE) (required).

### CODE REVIEW

File: network/proxy.go [hunk 1]
```diff
@@ -553,9 +553,14 @@ func (pr *Proxy) PassThroughToClient(conn *ConnWrapper, stack *Stack) *gerr.Gate
...
-	errVerdict := pr.sendTrafficToClient(conn.Conn(), response, received)
-	span.AddEvent("Sent traffic to client")
+	var errVerdict *gerr.GatewayDError
+	if received > 0 {
+		// Send the response to the client.
+		errVerdict = pr.sendTrafficToClient(conn.Conn(), response, received)
+		span.AddEvent("Sent traffic to client")
+	} else {
+		span.AddEvent("No data to send to client")
+	}
```
Comment (mostafa) [inline network/proxy.go:563]: I initially assumed that each request to PostgreSQL would have a response, but I was proven wrong by the [`COPY` command](https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-COPY). When the client sends a `COPY` command to the server (postgres), the server will reply with a `CopyInResponse` command, and provided that no errors happen anywhere in our systems, the client starts sending `CopyData` requests, which might be more than one request depending on the chunk size. After each `CopyData` request nothing is sent back by the server (no notification of receiveing the requests), until the client sends a `CopyDone` message at the end of all the `CopyData` requests. Only then the server responds with a `CommandComplete` and a `ReadyForQuery` response. Thus, the client might send multiple requests without receiving a response after each one. And the `ReadyForQuery` response from the server causes the client to start sending the next request.

Ref: https://www.postgresql.org/docs/current/protocol-message-formats.html

File: network/client.go [hunk 2]
```diff
@@ -240,19 +240,19 @@ func (c *Client) Receive() (int, []byte, *gerr.GatewayDError) {
...
 			span.RecordError(err)
-			return received, buffer.Bytes(), gerr.ErrClientReceiveFailed.Wrap(err)
+			return total, buffer.Bytes(), gerr.ErrClientReceiveFailed.Wrap(err)
 		}
-		received += read
+		total += read
 		buffer.Write(chunk[:read])
 
-		if read == 0 || read < c.ReceiveChunkSize {
+		if total == 0 || read < c.ReceiveChunkSize {
```
[the remark this answers is not in the document]
Comment (mostafa) [reply network/client.go]: Addressed in https://github.com/gatewayd-io/gatewayd/pull/610/commits/4c19dbca6b33d2eba420fff06c6780c5e601249b.

File: network/proxy.go [hunk 3]
```diff
@@ -713,10 +718,10 @@ func (pr *Proxy) receiveTrafficFromClient(conn net.Conn) ([]byte, *gerr.GatewayD
 			return chunk[:read], gerr.ErrReadFailed.Wrap(err)
 		}
 
-		received += read
+		total += read
 		buffer.Write(chunk[:read])
 
-		if received == 0 || received < pr.ClientConfig.ReceiveChunkSize {
+		if total == 0 || read < pr.ClientConfig.ReceiveChunkSize {
```
[the remark this answers is not in the document]
Comment (mostafa) [reply network/proxy.go]: Addressed in https://github.com/gatewayd-io/gatewayd/pull/610/commits/4c19dbca6b33d2eba420fff06c6780c5e601249b.

File: network/proxy.go [hunk 4]
```diff
@@ -553,9 +553,14 @@ func (pr *Proxy) PassThroughToClient(conn *ConnWrapper, stack *Stack) *gerr.Gate
 		span.AddEvent("Plugin(s) modified the response")
 	}
 
-	// Send the response to the client.
-	errVerdict := pr.sendTrafficToClient(conn.Conn(), response, received)
-	span.AddEvent("Sent traffic to client")
+	var errVerdict *gerr.GatewayDError
+	if received > 0 {
+		// Send the response to the client.
+		errVerdict = pr.sendTrafficToClient(conn.Conn(), response, received)
```
Comment (sinadarbouy) [inline network/proxy.go:559]: I’m not sure we need to run the OnTrafficToClient hooks if sendTrafficToClient fails. If we do need it, we can handle this block like this:
```		
	if received > 0 {
		errVerdict = pr.sendTrafficToClient(conn.Conn(), response, received)
		if errVerdict != nil {
			span.RecordError(errVerdict)
			span.AddEvent("Failed to send traffic to client")
		} else {
			span.AddEvent(fmt.Sprintf("Sent %d bytes of traffic to client", received))
		}
	} else {
		span.AddEvent("No data to send to client")
	}
	
```
If we don’t need it, I think we can change the logic like this:
```
	if received == 0 {
		span.AddEvent("No data to send to client")
		return nil
	}

	// Send the response to the client.
	errVerdict := pr.sendTrafficToClient(conn.Conn(), response, received)
	if errVerdict != nil {
		span.RecordError(errVerdict)
		span.AddEvent("Failed to send traffic to client")
		return errVerdict
	}

	span.AddEvent(fmt.Sprintf("Sent %d bytes of traffic to client", received))
```

Comment (mostafa) [reply network/proxy.go]: Addressed in https://github.com/gatewayd-io/gatewayd/pull/610/commits/15c3ad0cee46d91410b81e169c611c54f03eaf20.

**Review by sinadarbouy — APPROVED** [review]
LGTM🎉 Great catch and fix
